const icons = {
    return: 'mdi mdi-arrow-u-left-bottom',
    payment:'mdi mdi-cash',
    paymentList: 'mdi-playlist-check',
    hasReturn: 'mdi mdi-alpha-r-circle-outline',
    print: 'mdi-printer',
    filter: 'mdi-filter',
    close: 'mdi-close',
    filterOff: 'mdi-filter-off',
    product: 'mdi-wallet-giftcard',
    purchase: 'mdi-package-down',
    sale: 'mdi-package-up',
    brand: 'mdi-company',
    units: 'mdi-lan',
    unit_mapping: 'mdi-axis-y-arrow',
    product_units: 'mdi-axis-y-arrow',
    warranty: 'mdi-license',
    damages: 'mdi-image-broken-variant',
    customer: 'mdi-account-multiple-plus-outline',
    supplier: 'mdi-account-multiple-minus-outline',
    convert: 'mdi mdi-arrow-decision-auto',
    warehouse: 'mdi-home',
    category: 'mdi-list',
    expense: 'mdi-currency-usd-off',
    create: 'mdi-plus',
    list: 'mdi-list',
    employee_manager: 'mdi-account-cog',
    manage: 'mdi-hammer-wrench',
    add: 'mdi-sticker-plus-outline',
    calculator: 'mdi-calculator',
    setting: 'mdi-tools',
    delete: 'mdi-delete',
    edit: 'mdi-pencil',
    search: 'mdi-magnify',
    collapse: 'mdi-arrow-collapse-vertical',
    homeGroup:'mdi mdi-home-group',
    accountHat:'mdi mdi-account-hard-hat',
    submitButton: {
        new: 'mdi-plus',
        print: 'mdi-printer',
        view: 'mdi-eye'
    },
};
export default icons
