# Set the base image
FROM node:20

# Set working directory
WORKDIR /home/sharif/xeroinput/Inventory/

# Copy `package.json` and `package-lock.json`
COPY package.json package.json
COPY package-lock.json package-lock.json

# Install project dependencies
RUN npm install

# Copy project files into the docker image
COPY . .

# Expose the port Vite runs on
EXPOSE 3000

# Start the Vite server
CMD ["npm", "run", "dev"]