services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    tty: true
    build:
      context: ../
      dockerfile: Deploy/Dockerfile
    # allocate as many volumes as necessary, if needed.
    volumes:
      - ../Backend/storage/app:/var/www/html/storage/app
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
#      APP_VERSION: ${APP_VERSION}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
#      MAIL_MAILER: ${MAIL_MAILER}
#      MAIL_HOST: ${MAIL_HOST}
#      MAIL_PORT: ${MAIL_PORT}
#      MAIL_USERNAME: ${MAIL_USERNAME}
#      MAIL_PASSWORD: ${MAIL_PASSWORD}
#      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
#      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
#      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    ports:
      - "8080:80"
    networks:
      - n-laravel
    depends_on:
      - database

  database:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'laravel-mysql:/var/lib/mysql'
    networks:
      - n-laravel

networks:
  n-laravel:
    driver: bridge

volumes:
  laravel-mysql:
    driver: local